### ISSUE TITLE
Write SQL scripts to create and delete database

### ISSUE THREAD

**Issue by elliot-huck** [bangazon-clumsy-penguins/BangazonAPI#19]
#### Description
Create two .sql files. The first file should create and add all the tables with their Foreign Key constraints. The second file should delete any information in the tables, drop the Foreign Key constraints, and then drop the tables

#### Files
bangazon.sql and delete-bangazon.sql

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Create all tables in bangazon.sql
- [x] Delete and drop all tables in delete-bangazon.sql

**Comment by awieckert** [comment]
Pull down bracnh, was able to create and delete all tables in DB 👍
